### PR TITLE
Modified ScalerCH to allow for plotting selected channels.

### LINKED ISSUE #12: How to record certain scaler channels but not plot them?
Some combination of read_attrs and hints.  Need to better understand how hints work.

### PR DESCRIPTION
**Pull request by gfabbris**
This should resolve #12, but we may want to discuss here the best way to implement it.

I modified the way that `hints` is created from the various `channel.kind`. In `ScalerCH`, both the `read_attrs` and `hints` select the channels that are both `hinted` and `normal`, because by design: `Kind.hinted & Kind.normal = True`. The only way I found to differentiate these two is through their _value_: `Kind.hinted.value = 5` and `Kind.normal.value = 2` (kind can be both `normal` and `hinted`, then `value = 7`), but there may be a more sophisticated way to do this.

Then we are left with how to modify the `channel.kind` to reflect what we want. I implemented this with a `select_plot_channels`, which is a modified version of `select_channels`.

### CODE REVIEW

**Comment by gfabbris** [comment]
I just realized that there's an issue here. Running the _select_plot_channel_ will change omitted channels (which should not be saved during the scan) to normal (and thus saved).

I'll fix this tomorrow.

**Comment by prjemian** [comment]
Makes sense. Perhaps select channels needed changes, too?

**Comment by gfabbris** [comment]
I fixed `select_plot_channels` so that it won't change the `kind` if it is `omitted` (unless it is the channel selected to be plotted).

I also tweaked the `select_channels` so that it will add the currently selected channels if `hints['fields']` is empty.

**Comment by gfabbris** [comment]
I've written a first interaction of a callback function to plot the absorption spectra ([here](https://github.com/APS-4ID-POLAR/ipython-polar/blob/energy-scan/profile_bluesky/startup/instrument/callbacks/xanes_plot.py)). In this process, I realized that we need a way to keep track of a _monitor_ detector, because when we measure in transmission, the absorption coefficient is _log(monitor/detector)_.

I'm not sure where it is best to add this monitor. But, as I understand, we can populate the `ScalerCH.hints` in sort of whatever way we want, so I'm thinking to add a `{'monitor': ...}` to it. So that we can have an energy scan function that would look like `energy_scan([dets],E0,Ef,steps,monitor=None,md=None)`, and if nothing is passed to `monitor`, it will try to read it from `dets`. This would work fine when all our detectors belong to one scaler channel, but it may get tricky if different types of detectors are involved.

**Comment by gfabbris** [comment]
Also, we need to add the ability to count over monitor. I think we can use the _gate_ of each scaler channel for that.

**Comment by gfabbris** [comment]
Should we use a user calc to use as monitor for plot?

**Comment by gfabbris** [comment]
@prjemian and @CrI3 

I think this is in a good state for you to review it.

In this last commit I modified `LocalScalerCH` to handle counting over monitor. The main additions are the `LocalScalerCH.select_monitor` function, which toggles the scaler gates, and the `LocalScalerCH.preset_value` attribute that changes the monitor channel preset. Note that this applies also to the _Time_ channel.

Another change is that I added an `absorption_calc` device that calculates the _log(I0/I)_. We can then save all scaler channels, but plot only the absorption using the `BestEffortCallback` if we do:

```
dets = [scalerd,absorption_calc]
scalerd.select_channels(None)
scalerd.select_plot_channels([''])
```

I tested these changes at the beamline and it seems to work.

**Comment by prjemian** [comment]
too fast for me this AM, twas a late night

**Pull request merged**
